name: 'Run bundler-audit with reviewdog'
description: 'Run bundler-audit with reviewdog'
author: 'supermomonga'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'warning'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review,github-check]'
    default: 'github-pr-check'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'shield'
  color: 'red'
