name: 'Run bundler-audit with reviewdog'
description: 'Run bundler-audit and report results with reviewdog'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'warning'
  reporter:
    description: 'Reporter of reviewdog'
    default: 'github-pr-check'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'red'
