name: Test
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  test-bundler-audit:
    name: Test default settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test default settings
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
